# Generated by Django 3.0.8 on 2020-08-01 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='listings',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_image', models.URLField(blank=True)),
                ('item_title', models.CharField(max_length=128)),
                ('item_des', models.TextField()),
                ('item_price', models.FloatField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('item_category', models.CharField(choices=[('FS', 'Fashion'), ('EC', 'Electronics'), ('BE', 'Beauty'), ('HF', 'Home & Furniture'), ('SP', 'Sports'), ('BK', 'Books'), ('CR', 'Cars')], max_length=2)),
                ('avail_item', models.BooleanField(default=True)),
            ],
        ),
    ]
