# Generated by Django 3.0.8 on 2020-08-03 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bid_comments_listings'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listings',
            name='item_category',
            field=models.CharField(choices=[('FS', 'Fashion'), ('EC', 'Electronics'), ('BE', 'Beauty'), ('HF', 'Home & Furniture'), ('SP', 'Sports'), ('BK', 'Books'), ('CR', 'Cars'), ('OT', 'Others')], max_length=2),
        ),
    ]
