# Generated by Django 3.0.8 on 2020-08-03 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20200803_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='item_winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Winner', to=settings.AUTH_USER_MODEL),
        ),
    ]
