# Generated by Django 3.0.8 on 2020-08-06 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listings_item_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='watch_list',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
