# Generated by Django 3.0.8 on 2020-08-06 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20200806_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch_list',
            name='watch_list_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.listings'),
        ),
    ]
