# Generated by Django 3.0.8 on 2020-08-08 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20200808_0605'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='item_starting_bid',
            field=models.FloatField(null=True),
        ),
    ]
