# Generated by Django 3.1 on 2020-08-15 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20200813_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch_list',
            name='watchlistuser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
