# Generated by Django 3.1 on 2020-08-16 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_watch_list_watchlistuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='c_listings',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='auctions.listings'),
        ),
        migrations.AddField(
            model_name='comments',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='comments',
            name='user_commented',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
